# Sensible Settings
# Mouse Mode
set -g mouse on

# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0

# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 5

# (OS X) Fix pbcopy/pbpaste for old tmux versions (pre 2.6)
set -g default-command "reattach-to-user-namespace -l $SHELL"

# Upgrade $TERM
set -g default-terminal "screen-256color"

# Focus events enabled for terminals that support them
set -g focus-events on

# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on

# Uninstall key binding remap for tpm
set -g @tpm-clean 'u'

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse

# rebind resize key on macOS
bind j resize-pane -D 5
bind k resize-pane -U 5
bind l resize-pane -R 5
bind h resize-pane -L 5

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# List of plugins
set -g @plugin 'dracula/tmux' # dracula theme for status bar
set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions for you every 15 minutes
set -g @plugin 'jaclu/tmux-menus' # help menus for tmux
set -g @plugin 'tmux-plugins/tmux-yank' # copy to system clipboard

# Dracula status bar customizations
set -g @dracula-plugins "git cwd cpu-usage ram-usage weather battery time"

set -g @dracula-show-empty-plugins false
# cpu usage widget
set -g @dracula-cpu-usage-label " "
# ram usage widget
set -g @dracula-ram-usage-label " "
# battery widget
set -g @dracula-battery-label false
set -g @dracula-show-battery-status true
# network widget (issue with macos - shows ssid redacted)
# set -g @dracula-network-hosts "1.1.1.1 8.8.8.8"
# set -g @dracula-network-ethernet-label "󰈀 Eth"
# set -g @dracula-network-offline-label "󱍢 "
# set -g @dracula-network-wifi-label " "
# weather widget
set -g @dracula-show-fahrenheit false
set -g @dracula-fixed-location "Chirkunda"
set -g @dracula-show-location false
set -g @dracula-weather-hide-errors true
# time widget
set -g @dracula-show-timezone false
set -g @dracula-day-month true

# resurrect options
set -g @resurrect-capture-pane-contents 'on'

# continuum options
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
